name: Feature Request
description: Sugira uma nova funcionalidade ou melhoria.
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma melhoria para o studyhub!  Descreva a
        funcionalidade desejada e como ela beneficiaria os usuários.
  - type: textarea
    id: description
    attributes:
      label: Descrição da funcionalidade
      description: O que você gostaria de ver implementado?
      placeholder: Descreva a proposta em detalhes
      value: ""
    validations:
      required: true
  - type: input
    id: motivation
    attributes:
      label: Motivação
      description: Por que essa funcionalidade é útil?  Qual problema ela resolve?
      placeholder: Explique a relevância
      value: ""
    validations:
      required: true