name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci

      - name: Lint and type check
        run: |
          cd frontend && npm run lint
          cd ../backend && npm run lint

      - name: Run unit tests
        run: |
          cd frontend && npm test --if-present
          cd ../backend && npm test --if-present

      - name: Build frontend and backend
        run: |
          cd frontend && npm run build
          cd ../backend && npm run build --if-present